CREATE TABLE IF NOT EXISTS public.reviews (
    review_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    review_text text NOT NULL,
    review_date date DEFAULT CURRENT_DATE,
    inv_id integer NOT NULL,
    account_id integer NOT NULL,
    CONSTRAINT reviews_pkey PRIMARY KEY (review_id)
);